[[main]]
  name = "Docs"
  url = "docs/getting-started/home/"
  weight = 10

[[main]]
  name = "Sobre"
  url = "sobre/"
  weight = 20

[[main]]
  name = "Extra"
  weight = 30
  identifier = "extra"

[[main]]
  name = "Contribuir"
  weight = 40
  identifier = "contribuir"
  url = "guias/contribuir/"
  parent = "extra"

[[main]]
  name = "MarkDown Guide"
  weight = 50
  identifier = "markdown"
  url = "guias/markdown/"
  parent = "extra"

[[main]]
  name = "¿Que es LaTex?"
  weight = 60
  identifier = "latex"
  url = "guias/latex/"
  parent = "extra"

[[main]]
  name = "Agradecimientos"
  weight = 70
  identifier = "agradecimientos"
  url = ""
  parent = "extra"
