# Meta Data for SEO

## Homepage
title = "M4t∈DΘks"
titleSeparator = "-"
titleAddition = "Apunte digital de Matematica"
description = "M4t∈DΘKs en un apunte digital de Matematica de libre contribucion para el uso, primariamente, en OMA (Olimipiada Matematica Argentina)"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaName = "MateDoks"
schemaLocale = "es-AR"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaGitHub = "https://github.com//matedoks"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Copyright (c) 2022 MateDoks"

# Feed
copyRight = "Copyright (c) 2022 MateDoks"

# Alert
alert = false
alertDismissable = true
alertText = "Bienvenidos a MateDoks"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/zaitam/MateDoks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
