name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the project
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Run test script
      run: npm test

    - name: Build production website
      run: npm run build
